//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TbcTaskApi.Shared.ValidationResponseMessages {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResponseMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponseMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TbcTaskApi.Shared.ValidationResponseMessages.ResponseMessages", typeof(ResponseMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ValidationGeneralError {
            get {
                return ResourceManager.GetString("ValidationGeneralError", resourceCulture);
            }
        }
        
        internal static string NameLengthError {
            get {
                return ResourceManager.GetString("NameLengthError", resourceCulture);
            }
        }
        
        internal static string GenderValidationError {
            get {
                return ResourceManager.GetString("GenderValidationError", resourceCulture);
            }
        }
        
        internal static string PersonalNumberValidationError {
            get {
                return ResourceManager.GetString("PersonalNumberValidationError", resourceCulture);
            }
        }
        
        internal static string AgeValidationError {
            get {
                return ResourceManager.GetString("AgeValidationError", resourceCulture);
            }
        }
        
        internal static string PhoneValidationError {
            get {
                return ResourceManager.GetString("PhoneValidationError", resourceCulture);
            }
        }
        
        internal static string NameLetterValidationErrorMessage {
            get {
                return ResourceManager.GetString("NameLetterValidationErrorMessage", resourceCulture);
            }
        }
        
        internal static string UserAlreadyExistsMessage {
            get {
                return ResourceManager.GetString("UserAlreadyExistsMessage", resourceCulture);
            }
        }
        
        internal static string UserNotFoundMessage {
            get {
                return ResourceManager.GetString("UserNotFoundMessage", resourceCulture);
            }
        }
        
        internal static string ConnectionExists {
            get {
                return ResourceManager.GetString("ConnectionExists", resourceCulture);
            }
        }
        
        internal static string ConnectionCreatedSuccess {
            get {
                return ResourceManager.GetString("ConnectionCreatedSuccess", resourceCulture);
            }
        }
        
        internal static string UserDeleteSuccess {
            get {
                return ResourceManager.GetString("UserDeleteSuccess", resourceCulture);
            }
        }
        
        internal static string PhotoSaveError {
            get {
                return ResourceManager.GetString("PhotoSaveError", resourceCulture);
            }
        }
        
        internal static string PhotoUploadedSuccess {
            get {
                return ResourceManager.GetString("PhotoUploadedSuccess", resourceCulture);
            }
        }
        
        internal static string ConnectedPersonDoesnotExistException {
            get {
                return ResourceManager.GetString("ConnectedPersonDoesnotExistException", resourceCulture);
            }
        }
    }
}
